### ISSUE TITLE
Plans or releasing 1.0.0?

### ISSUE THREAD

**Issue by bconoly** [williewheeler/kite#5]
I realize the last commit was over a year ago but I'd really like to use this library.  Do you have any plans to perform a release of your 1.0.0 version into a public maven repository?

**Comment by williewheeler** [comment]
Yeah. I was working on a book that took up most of my time, but that's done now, so I do plan to come back to this project. I don't have an ETA right now though. Is there a specific time when you would need a 1.0?

**Comment by bconoly** [comment]
If we're going to use it we would need the v1 by August.  I certainly would love to take advantage of it as it seems like an extremely elegant solution to what we need.  Thanks
